# Generated by Django 5.1.3 on 2026-05-29 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('reading', models.CharField(blank=True, default='', max_length=200)),
                ('meaning_vi', models.TextField()),
                ('example', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('TOEIC', 'TOEIC Business'), ('JLPT_N5', 'JLPT N5'), ('JLPT_N4', 'JLPT N4'), ('JLPT_N3', 'JLPT N3'), ('JLPT_N2', 'JLPT N2'), ('JLPT_N1', 'JLPT N1'), ('Programming', 'Programming')], default='TOEIC', max_length=20)),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vocabulary',
                'ordering': ['category', 'word'],
                'unique_together': {('word', 'category')},
            },
        ),
        migrations.CreateModel(
            name='UserVocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learned_at', models.DateTimeField(auto_now_add=True)),
                ('next_review', models.DateField(blank=True, null=True)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval_days', models.IntegerField(default=1)),
                ('correct_count', models.IntegerField(default=0)),
                ('wrong_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_progress', to=settings.AUTH_USER_MODEL)),
                ('vocab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='vocabulary.vocabulary')),
            ],
            options={
                'db_table': 'user_vocabulary',
                'ordering': ['next_review'],
                'unique_together': {('user', 'vocab')},
            },
        ),
    ]
