# Generated by Django 5.1.3 on 2026-05-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('TOEIC', 'TOEIC'), ('Japanese', 'Japanese'), ('Programming', 'Programming'), ('Other', 'Other')], default='TOEIC', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_min', models.IntegerField(default=0)),
                ('xp_earned', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'study_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(choices=[('TOEIC', 'TOEIC'), ('Japanese', 'Japanese'), ('Programming', 'Programming'), ('Other', 'Other')], default='TOEIC', max_length=20)),
                ('scheduled_date', models.DateField()),
                ('time_slot', models.TimeField(blank=True, null=True)),
                ('duration_min', models.IntegerField(default=30)),
                ('color', models.CharField(default='#3B82F6', max_length=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'study_tasks',
                'ordering': ['scheduled_date', 'time_slot'],
            },
        ),
    ]
